### ISSUE TITLE
Tester si un identifiant est déjà prit ou non

### ISSUE THREAD

**Issue by LastCoder25** [LastCoder25/Evolva-Php-REST#1]
Je veux créer la requête qui va checker si un identifiant existe déjà ou non.
Je pensais faire un get en passant en paramètre l'identifiant à tester. Si la requête retourne une ligne c'est que l'identifiant est prit.
J'ai essayé de faire passer un string et un objet mais rien à faire.

**Comment by viasisco** [comment]
Fait voir la requête en question. Comment passes tu l'id? dans l'url ou dans un json?

**Comment by LastCoder25** [comment]
J'ai testé les deux ci-dessous :
$route['user/check']['GET'] = 'userCtrl/checkIdentifiant';
ET
$route['user/check/:identifiant']['GET'] = 'userCtrl/checkIdentifiant/$identifiant';

**Comment by viasisco** [comment]
tu l'as mis dans quelle branche? develop?

**Comment by LastCoder25** [comment]
La première version y est oui.

**Comment by viasisco** [comment]
je t'ai commité les modifs dans la branche develop.
Dans le fichier **routes.php** 
```
$route['user/(:num)']['GET'] = 'userCtrl/checkIdentifiant/$1';
```
Dans le controller **userCtrl.php** : 
```
public function checkIdentifiant($identifiant)
```

**Comment by LastCoder25** [comment]
![err](https://cloud.githubusercontent.com/assets/23555621/24153953/1e4ec95a-0e50-11e7-8bb0-9fc55e3d7c33.PNG)

**Comment by viasisco** [comment]
Il faut que tu règles ton serveur Apache pour le CORS.

**Comment by LastCoder25** [comment]
J'avais rajouté deux lignes dans le constructeur de chaque controller : 
class UserCtrl extends CI_Controller
{
	/**
	Constructor that loads models and libraries
	*/
	public function __construct()
	{
		header('Access-Control-Allow-Origin: *');
		header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
		parent::__construct();
		$this->load->library('jsonbourne');        //logical class to deal with json
		$this->load->model('userModel');        // data layer
	}

Ça ne suffit pas ?

**Comment by LastCoder25** [comment]
J'ai rajouté les 2 lignes comme ici : 
http://www.competa.com/blog/enable-cors-origin-resource-sharing-on-codeigniter-rest-server/

**Comment by viasisco** [comment]
en fait tout va se passer AVANT d'arriver au controleur.  Au niveau du serveur APACHE. 
Je clos l'issue pour distinguer les issues, car nous sommes dans 2 problèmes différents.
